name: Mob Squad
favicon: null
layout_spectrum: 0.7980662186164409
typography_spectrum: 0.07515033194795251
title: Las Vegas Soccer Supporters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#be2431'
    - '#6f6f6f'
    - '#afafaf'
  brandStrength: 0.42999480315484107
  lightness: 0.2771183925215155
  saturation: 0.8398878972511739
  rhythmicContrast: 0.09974834253080189
purpose: []
